# Generated by Django 5.2.14 on 2026-05-20 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ScanSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("target", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "pending"),
                            ("running", "running"),
                            ("completed", "completed"),
                            ("failed", "failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "nmap_flags",
                    models.CharField(
                        default="-sV -sC --open",
                        help_text="Additional nmap flags",
                        max_length=500,
                    ),
                ),
                ("dir_wordlist", models.CharField(blank=True, max_length=500)),
                ("dns_wordlist", models.CharField(blank=True, max_length=500)),
                ("task_id", models.CharField(blank=True, max_length=255)),
                ("error_message", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PortResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("port", models.IntegerField()),
                ("protocol", models.CharField(default="tcp", max_length=10)),
                ("state", models.CharField(max_length=20)),
                ("service", models.CharField(blank=True, max_length=100)),
                ("product", models.CharField(blank=True, max_length=200)),
                ("version", models.CharField(blank=True, max_length=100)),
                ("extra_info", models.TextField(blank=True)),
                ("is_http", models.BooleanField(default=False)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ports",
                        to="core.scansession",
                    ),
                ),
            ],
            options={
                "ordering": ["port"],
            },
        ),
        migrations.CreateModel(
            name="DNSResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subdomain", models.CharField(max_length=500)),
                (
                    "record_type",
                    models.CharField(
                        choices=[
                            ("A", "A"),
                            ("AAAA", "AAAA"),
                            ("CNAME", "CNAME"),
                            ("MX", "MX"),
                            ("TXT", "TXT"),
                            ("NS", "NS"),
                            ("SOA", "SOA"),
                        ],
                        max_length=10,
                    ),
                ),
                ("value", models.CharField(max_length=500)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dns_records",
                        to="core.scansession",
                    ),
                ),
            ],
            options={
                "ordering": ["record_type", "subdomain"],
            },
        ),
        migrations.CreateModel(
            name="DirectoryResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.CharField(max_length=1000)),
                ("status_code", models.IntegerField()),
                ("size", models.IntegerField(default=0)),
                ("port", models.IntegerField(default=80)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="directories",
                        to="core.scansession",
                    ),
                ),
            ],
            options={
                "ordering": ["status_code", "url"],
            },
        ),
    ]
