# Generated by Django 5.2.14 on 2026-05-22 16:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="scansession",
            name="dns_pid",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="scansession",
            name="gobuster_pid",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="scansession",
            name="nmap_pid",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="scansession",
            name="nmap_flags",
            field=models.CharField(
                default="-T4 --open", help_text="Additional nmap flags", max_length=500
            ),
        ),
    ]
