# Generated by Django 5.2.14 on 2026-05-23 08:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_scansession_dns_pid_scansession_gobuster_pid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scansession",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "pending"),
                    ("running", "running"),
                    ("stopping", "stopping"),
                    ("stopped", "stopped"),
                    ("completed", "completed"),
                    ("failed", "failed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
