# Generated by Django 5.2.14 on 2026-05-24 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_alter_scansession_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="scansession",
            name="vhost_pid",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="scansession",
            name="vhost_wordlist",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.CreateModel(
            name="VHostResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hostname", models.CharField(max_length=500)),
                ("port", models.IntegerField(default=80)),
                ("status_code", models.IntegerField(default=0)),
                ("content_length", models.IntegerField(default=0)),
                ("words", models.IntegerField(default=0)),
                ("lines", models.IntegerField(default=0)),
                ("title", models.CharField(blank=True, max_length=500)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vhosts",
                        to="core.scansession",
                    ),
                ),
            ],
            options={
                "ordering": ["hostname"],
            },
        ),
    ]
