# Generated by Django 5.2.14 on 2026-05-25 07:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_scansession_vhost_pid_scansession_vhost_wordlist_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="scansession",
            name="confirmed_domains",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="scansession",
            name="discovered_domains",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="scansession",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "pending"),
                    ("running", "running"),
                    ("awaiting_domains", "awaiting_domains"),
                    ("stopping", "stopping"),
                    ("stopped", "stopped"),
                    ("completed", "completed"),
                    ("failed", "failed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="scansession",
            name="vhost_wordlist",
            field=models.CharField(
                blank=True,
                default="/opt/SecLists/Discovery/DNS/subdomains-top1million-5000.txt",
                max_length=500,
            ),
        ),
    ]
