# Generated by Django 5.2.14 on 2026-05-25 10:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_scansession_confirmed_domains_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="scansession",
            name="dns_pid",
        ),
        migrations.RemoveField(
            model_name="scansession",
            name="gobuster_pid",
        ),
        migrations.RemoveField(
            model_name="scansession",
            name="nmap_pid",
        ),
        migrations.RemoveField(
            model_name="scansession",
            name="vhost_pid",
        ),
        migrations.RemoveField(
            model_name="vhostresult",
            name="title",
        ),
        migrations.AlterField(
            model_name="scansession",
            name="nmap_flags",
            field=models.CharField(default="-T4 --open", max_length=500),
        ),
        migrations.AlterField(
            model_name="scansession",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("running", "Running"),
                    ("awaiting_domains", "Awaiting domain confirmation"),
                    ("stopping", "Stopping"),
                    ("stopped", "Stopped"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
